image: node:8.4.0
# This ensures we do a full clone on each build which prevents issues when cross referencing
# changesets and releases
clone:
  depth: full
options:
  size: 2x

pipelines:
  branches:
    master:
      - step:
          script:
            # Note: in master, this script will rebase you onto latest origin/master
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd build/ci-scripts && bolt stop-if-older-build)
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test:ci:master
            - bolt test:browser:browserstack
            - bolt release
            - (cd build/ci-scripts && bolt restart-stopped-build)

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install --pure-lockfile
          # - bolt build
          # - bolt lint
          # - bolt typecheck
          - yarn jest --maxWorkers=2
          # - bolt test:browser:browserstack
          # - (cd website && bolt deploy-staging:no-minimize)

  custom: # Pipelines that can be scheduled or triggered manually

    # This should only be called by a scheduled build
    build-website-production:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd website && bolt deploy)
