image: node:8.4.0
# This ensures we do a full clone on each build which prevents issues when cross referencing
# changesets and releases
clone:
  depth: full
options:
  size: 2x

pipelines:
  branches:
    master:
      - step:
          script:
            # Note: in master, this script will rebase you onto latest origin/master
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd build/ci-scripts && yarn stop-if-older-build)
            - yarn build
            - yarn lint
            - yarn typecheck
            - yarn test
            - yarn test:browser:browserstack
            - yarn release
            - (cd build/ci-scripts && yarn restart-stopped-build)
          caches:
            - node

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install --pure-lockfile
          # - yarn build
          # - (node build/ci-scripts/should.run.js eslint) && yarn lint:eslint
          # - (node build/ci-scripts/should.run.js tslint) && yarn lint:tslint
          # - (node build/ci-scripts/should.run.js flow) && yarn typecheck:flow
          # - (node build/ci-scripts/should.run.js tsc) && yarn typecheck:typescript
          # - yarn test:changed
          # - (node build/ci-scripts/should.run.js browserstack) && yarn test:browser:browserstack
          # - set -o pipefail && (cd website && yarn deploy-staging:no-minimize) | tee output.txt
          # - node build/ci-scripts/update.build.status.with.netlify.link.js
        caches:
          - node

  custom: # Pipelines that can be scheduled or triggered manually

    # This should only be called by a scheduled build
    build-website-production:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - (cd website && yarn deploy)
          caches:
            - node

    # This will run with the webdriver tests
    build-webdriver:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn test:webdriver:browserstack

    # This will run essentially the branch builds, but without any optimizations and should be manually
    # run in any potentially risky builds
    run-full-suite:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install --pure-lockfile
            - yarn build
            - yarn lint
            - yarn typecheck
            - yarn test
            - yarn test:browser:browserstack
            - (cd website && yarn deploy-staging:no-minimize)
    # We deliberately don't use the cache here as well

    landkid:
      - step:
          script:
            - source ./build-setup.sh
            - git merge master --no-edit
            - bolt install --pure-lockfile
            - yarn build
            - yarn lint
            - yarn typecheck
            - yarn test
            - yarn test:browser:browserstack

    # This build should only be run on the master branch, once per day.
    # It manually clears the cache and runs a very quick
    reseed-pipelines-cache:
      - step:
          script:
            - source ./build-setup.sh
            - git merge master --no-edit
            - bolt install --pure-lockfile
            - yarn build
            - yarn lint
            - yarn typecheck
            - yarn test
            - yarn test:browser:browserstack
