image: node:8.4.0
pipelines:
  branches:
    master:
      - step:
          script:
            - source ./build-setup.sh
            - bolt install
            - bolt build
            - bolt lint
            - bolt typecheck
            - bolt test
            - bolt test:browser:browserstack
            - bolt release
            - (cd website && bolt deploy)

  default:
    - step:
        script:
          - source ./build-setup.sh
          - bolt install
          - node ./npm-info.js
